Make taxcalc an `extra_require`
`taxcalc` was previously an `install_requires`, meaning Python tries to install it if not already installed when installing `microdf`. This has caused issues like this in Google Colab:
```
pip install git+git://github.com/maxghenis/microdf.git
Collecting git+git://github.com/maxghenis/microdf.git
  Cloning git://github.com/maxghenis/microdf.git to /tmp/pip-req-build-7dh2hrg_
  Running command git clone -q git://github.com/maxghenis/microdf.git /tmp/pip-req-build-7dh2hrg_
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from microdf==0.1) (1.16.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from microdf==0.1) (0.24.2)
Collecting taxcalc (from microdf==0.1)
  Using cached https://files.pythonhosted.org/packages/53/d8/ff91d027c83a4a780532e1d3dbee13e26d214a7fba90c8f21980e38ec9c8/taxcalc-0.7.82.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Moving it to `extras_require` should fix this.